# Site settings
title: Packlist Test
tagline: "A test site for experimentation with Jekyll"
# url:  # The base hostname & protocol for your site. Use it if you need absolute URL's

# Site collections
collections:
  animals:
    output: true

defaults:
  - scope:
      path: ""
      type: "animals"
    values:
      layout: animal

# Social
socialimg: /images/social.jpg # be sure to change this image
facebook: fbusername
twitter: twusername
github: ghusername
googleplus: gusername
instagram: igusername

# Contact
phone: "555-555-5555" # Temp phone number
email: "jasonhenrymarsh@gmail.com"

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
